server:
   port: 1443
   ssl:
      key-store: keystore.p12
      key-store-password: Iamcool
      keyStoreType: PKCS12
      keyAlias: tomcat

ldap:
   urls: ldap://ldap.forumsys.com:389/
   base: dc=example,dc=com
   username: cn=read-only-admin,dc=example,dc=com
   password: password
   pattern: uid={0}
